name: Build and Release Desktop Apps

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd planner
          npm install
          npm run build
          cd ../planner-desktop
          npm install

      - name: Build desktop app
        run: |
          cd planner-desktop
          node copy-build.js
          npm run build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            planner-desktop/dist/*.exe
            planner-desktop/dist/*.dmg
            planner-desktop/dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 